# Generated by Django 6.0.1 on 2026-01-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12)),
                ('birthday', models.DateField()),
                ('gender', models.BooleanField()),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
