# Generated by Django 6.0.1 on 2026-01-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0003_userinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/'),
        ),
    ]
